language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

codecov: true

jobs:
  include:
    - os: windows
      arch: x86
      julia: 1.0
      name: "Julia: 1.0 (32bit)"
    - os: windows
      arch: x86
      julia: 1.1
      name: "Julia: 1.1 (32bit)"
    - os: windows
      arch: x86
      julia: 1.2
      name: "Julia: 1.2 (32bit)"
    - os: windows
      arch: x86
      julia: nightly
      name: "Julia: nightly (32bit)"
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("DustExtinction")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
