language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
git:
  depth: 999999
notifications:
  email: false


jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      env:
        - DOCUMENTER_DEBUG=true
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
