language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.4
  - nightly

env:
  - DATADEPS_ALWAYS_ACCEPT=true

notifications:
  email: false

codecov: true

cache:
  directories:
    - $HOME/.julia/datadeps

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
