language: julia

os:
  - linux
  - osx
  - freebsd

julia:
  - 1.0
  - 1.4
  - nightly

env:
  - DATADEPS_ALWAYS_ACCEPT=true

notifications:
  email: false

cache:
  directories:
    - $HOME/.julia/datadeps
    - $HOME/.julia/artifacts

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          include("docs/make.jl")'
      after_success: skip

after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
