name = "DustExtinction"
uuid = "fb44c06c-c62f-5397-83f5-69249e0a3c8e"
license = "MIT"
version = "0.4.0"

[deps]
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"

[compat]
FITSIO = "≥ 0.13.0"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"

[targets]
test = ["Test", "Measurements"]
