name: CompatHelper

on:
  schedule:
    - cron: '05 20 */5 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: "Install CompatHelper"
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: "Run CompatHelper"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        shell: julia --color=yes {0}
        run: using CompatHelper; CompatHelper.main()
